(defun move-to-right-window-or-vsplit ()
  (interactive)
  (if (window-at-side-p nil 'right)
      (progn
	(split-window-right)
	(windmove-right)
	)
    (windmove-right))
  (golden-ratio)
  )
(defun move-to-bottom-window-or-hsplit ()
  (interactive)
  (if (window-at-side-p nil 'bottom)
      (progn
	(split-window-below)
	(windmove-down)
	)
    (windmove-down))
  (golden-ratio)
  )
(defun move-to-up-window-or-hsplit ()
  (interactive)
  (if (window-at-side-p nil 'top)
      (progn
	(split-window-below)
	)
    (windmove-up))
  (golden-ratio)
  )
(defun move-to-left-window-or-vsplit ()
  (interactive)
  (if (window-at-side-p nil 'left)
      (progn
	(split-window-right)
	)
    (windmove-left))
  (golden-ratio)
  )

(defun maybe-projectile-find-file ()
  (interactive)
  (call-interactively
   (if (projectile-project-p)
       #'counsel-projectile-find-file
       #'counsel-find-file)))
